### ISSUE TITLE
UnicodeEncodeError:

### ISSUE THREAD

**Issue by yoosee** [basuke/kanshin-export#1]
結構な頻度で UnicodeEncodeError が出ます。title が日本語の際にそこを parse しようとすると発生している気はしますが、再現性が100%ではなく、うまくいくこともあるのが理由がよく分かりません。

ID: 1142, KeywordID(発生時): 235049
- python              2.7.11-2  
- python-bs4          4.4.1-1  

```
Traceback (most recent call last):
  File "fetch.py", line 102, in <module>
    main(*sys.argv[1:])
  File "fetch.py", line 98, in main
    keywords = fetch_keywords(user_id)
  File "fetch.py", line 88, in fetch_keywords
    print keyword_id, keyword.title
  File "fetch.py", line 66, in title
    print self.content('h1.title')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-10: ordinal not in range(128)
```

**Comment by basuke** [comment]
Shellの環境で出るエラーですな。デバッグ用に出しているキーワードタイトルでエラーということは、ユニコードの出力の設定に違いがあってエラーに成ったりならなかったり。ターミナル変えてますか？

```
import sys
print sys.stdout.encoding
```

これ、何が出力されます？

**Comment by yoosee** [comment]
```
>>> print sys.stdout.encodng
UTF-8
```

です。なおstdoutをファイルに向ける、つまり `% python fetch.py 1142 > out.json` のようにすると、ほぼ確実に起きますが、そのまま出力させると10回に1回位失敗します。環境依存の問題な予感はするんだけど、他に使ってる python プログラムであまり見たこと無いんですよね。環境は素の Debian stretch, tmux 上の zsh に PuTTY 経由で ssh login での実行。

で、試しに 47行目を

```
          return result.get_text().strip().encode("utf-8")
```

としたらエラー出なくはなりました。

**Comment by basuke** [comment]
俺の理解だと、sys.stdoutにUnicodeが渡ってきたら自動的にencodingに変換してくれる、というものだったんだけど、イマイチ不安ね。そしたら、とりあえずdebug のprint出力をコメントアウトして様子見れますか？ 最後のJSONの出力では問題ないはず。

**Comment by yoosee** [comment]
上記の .encode("utf-8") を外して、main の print をコメントアウトして実行してみた場合は UnicodeEncodeError が出ます。

main の print をコメントアウトせず、class KeywordListPage 内の print をコメントアウトした場合にはエラーにならず、最後の json dump まで進みました。また `print self.content('h1.title')` を `print self.content('h1.title').encode("utf-8")` としてやる分にはエラーになりません。stdout を pipe した時になにか暗黙のエンコーディングがずれるとかが発生ししてるのかな。

一応思い立って環境変数をクリアした場合やzshではなくbashで実行するなども試しましたけど、問題の傾向は一緒ですね。

**Comment by yoosee** [comment]
`print sys.getdefaultencoding()` してみたら ascii が返ってきたので、私の環境の default encoding が ascii なのが多分エラーの原因ではあるようです。上記の変更なしに fetch.py に

```
import codecs
sys.stdout = codecs.getwriter('utf_8')(sys.stdout)
```

を入れてもエラーが出なくなりました。

**Comment by basuke** [comment]
Python 3 限定にしたんで、再度見てもらえます？

**Comment by yoosee** [comment]
python3 で問題なく動くっぽいです。何パターンか試しましたが上記のエラーは出なくなってます。

**Comment by basuke** [comment]
よかった。しかし、AWS Lambdaで動かすためには、最終的にはPython2.7に戻さなくてはいけないんだけどw とりあえず閉じます。
